services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:16.4-alpine
    container_name: crypto_news_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-55432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crypto_network

  # FastAPI Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: crypto_news_app
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      CRYPTO_PANIC_API_KEY: ${CRYPTO_PANIC_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app:ro
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - crypto_network

  # Background News Scheduler Service
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: crypto_news_scheduler
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      CRYPTO_PANIC_API_KEY: ${CRYPTO_PANIC_API_KEY}
    depends_on:
      app:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./scripts/news_scheduler.py:/app/news_scheduler.py:ro
    networks:
      - crypto_network

volumes:
  postgres_data:

networks:
  crypto_network:
    driver: bridge
